using YoutubeExplode.Videos.ClosedCaptions;

namespace Application.Helpers
{
    internal static class CaptionTrackSelector
    {
        public static ClosedCaptionTrackInfo? SelectPrimary(IReadOnlyList<ClosedCaptionTrackInfo> tracks)
        {
            if (tracks.Count == 0)
                return null;

            if (tracks.Count == 1)
                return tracks[0];

            var manualTracks = tracks.Where(t => !t.IsAutoGenerated).ToList();
            if (manualTracks.Count == 1)
                return manualTracks[0];

            // Fallback: no hay forma confiable de saber el idioma original
            // sin la API oficial de YouTube. Se asume que la primera pista
            // del manifiesto corresponde al audio principal del video.
            return tracks[0];
        }
    }
}
